### ISSUE TITLE
OpenRC integration

### ISSUE THREAD

**Issue by stalkerg** [dbus2/busd#141]
Maybe a little bit to early, but I want to use it for OpenRC installation (Gentoo or Alpine) instead default dbus.

**Comment by zeenix** [comment]
Great. Is this issue about packaging busd for them or are there some special requirements that need to be implemented?

**Comment by aidanharris** [comment]
I don't think anything special is needed here but it's important that features like #80 don't get implemented in a way that makes this useless to anyone else. It is very hard to run dbus-broker without Systemd (See: https://github.com/bus1/dbus-broker/issues/340) so most people using OpenRC continue to run the reference dbus-daemon instead.

In particular, if you do manage to get dbus-broker running you will find that user services do not launch because this is expected to be managed by Systemd (or some other "supervisor" or "manager" of some sort).

Whether you choose to tackle launching user services without Systemd like the reference implementation does is one thing but I would strongly suggest to at least keep it somewhat working without Systemd (even if users have to manually launch services somehow) and when you do add Systemd functionality to this project then gate it behind a Cargo 'systemd' feature flag so it's still possible to build without it.

**Comment by zeenix** [comment]
I can try but I won't make any promises. systemd (or at least its interfaces) should really be available on all Linux systems these days. Assuming systemd, makes things easier to implement.

Having said that, busd does target non-Linux machines so all the basics will continue to work w/o systemd.

**Comment by zeenix** [comment]
Closed since I don't see any actionable here.

**Comment by stalkerg** [comment]
> I can try but I won't make any promises. systemd (or at least its interfaces) should really be available on all Linux systems these days. Assuming systemd, makes things easier to implement.

Gentoo is still Linux, and they use OpenRC by default. And not only Gentoo but some other distros also use OpenRC.

**Comment by zeenix** [comment]
> > I can try but I won't make any promises. systemd (or at least its interfaces) should really be available on all Linux systems these days. Assuming systemd, makes things easier to implement.
> 
> Gentoo is still Linux, and they use OpenRC by default. And not only Gentoo but some other distros also use OpenRC.

I didn't say or imply otherwise but if they decide to go their own way, I (or any software developer targeting Linux in general) shouldn't have to cater for them.

Anyway, as I wrote, I seriously doubt we'll have a hard dep on systemd. As you wrote, maybe functionality like service autolaunch may not work but that's about it.

**Comment by zeenix** [comment]
Btw, I also get annoyed that I can't launch a new dbus-broker instance as easily as I can do for dbus-daemon so launching easily through commandline should always be possible.

**Comment by stalkerg** [comment]
@zeenix thank you! I appreciate your answer.
